name: 'Test Report Action'
description: 'Greet someone and record the time'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true 
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
  